name: Deploy checkout app

on:
  push:
    branches:
      - main
    paths:
      - 'shop-nextjs-mf-checkout/**'  

env:
  NODE_VERSION: '14.x'

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJs ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" > .npmrc 
          echo "@andreacaldera:registry=https://npm.pkg.github.com" >> .npmrc
          echo "@module-federation:registry=https://r.privjs.com" >> .npmrc
          echo "//r.privjs.com/:_authToken=${{ secrets.PRIVJS_TOKEN }}" >> .npmrc
          cp .npmrc shop-nextjs-mf-checkout/
          yarn
      - name: Code quality
        run:  |
          # yarn lint 
          # yarn build:ts
          # yarn build:ts
          # yarn test

      - name: Setup env variables
        run: |
          mv .env .env.local    
          mv .env.prod .env    
      
      - name: Deploy site to Vercel      
        uses: amondnet/vercel-action@v20
        with:
          working-directory: shop-nextjs-mf-checkout
          vercel-token: ${{ secrets.VERCEL_TOKEN }} 
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
